WerWolv/ImHex-Patterns

README.md, patterns/png.hexpat
This is an improved version of the pattern @fosterbrereton created in #18 with support for a few more PNG chunk types, automatic chunk counting, and commenting on variables
=> PNG Pattern

README.md, patterns/dds.hexpat
Adding pattern for DirectDraw Surface image type
=> patterns: Added DDS pattern

README.md, patterns/iso.hexpat
=> patterns: Added ISO pattern

patterns/wav.hexpat
Hi,
I've improved wav pattern for a bit.
=> patterns: improve WAV pattern

includes/std/mem.pat
Implemented function from https://github.com/WerWolv/ImHex/pull/448
=> patterns: add std::mem::find_sequence_in_range

patterns/wav.hexpat
* Consider appended padding, use chunk size.
* Fix to add 1 byte length for padding if chunk size is an odd number of bytes.
=> WAV: Fix related to chunk size.

patterns/elf.hexpat
Added structs to the body and renamed data_size -> size
=> Fixed: ELF 32-bit

patterns/png.hexpat
Note: This PR assumes the merger of #53.
=> patterns: png.hexpat: +sRGB, zTXt, tEXt

patterns/png.hexpat
https://github.com/WerWolv/ImHex-Patterns/issues/61
=> Fix PNG pattern #61

README.md, patterns/tar.hexpat
=> Add Tar Pattern

README.md, patterns/gif.hexpat
=> Add GIF pattern

README.md, patterns/zstd.hexpat
=> patterns/zstd: Added ZSTD pattern

patterns/gif.hexpat
- Improved git format with more explicit data structuring
- Added more formatting and data parsing
=> Improved gif format using more explicit formating styles

README.md, patterns/Crashlvl.hexpat
User created flashback tapes level format pattern.
From the fan game Crash Bandicoot - Back in Time
=> Added Crash Bandicoot - Back in time level format

patterns/java_class.hexpat
- Added all attributes according to the [Java SE 20 Standard](https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-4.html)
- Added display formatting with constantpool resolving
=> .class file improvement

patterns/macho.hexpat
Refer to LLVM's [document](https://llvm.org/doxygen/namespacellvm_1_1MachO.html#af2acbc063e449084ba33f738a700ce47)
=> Fix macho CpuType error and add CpuType::ARM64 and CpuType::ARM64_32

patterns/bmp.hexpat, patterns/gif.hexpat, patterns/jpeg.hexpat, patterns/png.hexpat, patterns/tga.hexpat
There were two patterns that couldnt have the visualizer integrated because they don't use a completed final pattern.
=> Added visualizers to image patterns

patterns/7z.hexpat
v1.01
--Minor changes.
--CompressData lenght added
--Output optimization
=> Update 7z.hexpat - v1.01

patterns/fdt.pat
Fix parsing to support multiple FDTs in a file and non-zero base addresses.
=> Fix flattened device tree parsing

includes/std/string.pat
Added the missing part at the end of the string after being replaced.
=> Fix for issue 1279

patterns/mp4.hexpat
Add support for stbl box in mp4
=> patterns: mp4. add stbl box

.gitmodules, README.md
Not sure whether you want the link text to be `patterns/ffx/*` or just `patterns/ffx` or smth, feel free to edit lol
=> Add Final Fantasy X patterns

includes/type/magic.pat
All credit goes to pxd at imhex discord
=> Changes to magic type to include address of failed asserts.

patterns/tar.hexpat
=> fix minor typo in tar pattern

includes/std/file.pat
Parody with https://github.com/WerWolv/PatternLanguage/pull/102
=> Add create_directories to std

README.md, patterns/fbx.hexpat
Added some improvements to the FBX pattern and fixed a syntax error in the readme file.
=> patterns/fbx: Improved the FBX pattern

themes/one_dark.json
This PR adds new dark theme to Content Store. It was inspired by Atom One Dark theme and aims to provide more gray colored experience and improve readability. Would definitely recommend for usage in 3 AM.
=> Added One Dark theme

includes/type/float16.pat
yes that is all. thank you have a good day
=> includes/type/float16: Fix error in format function

patterns/iso.hexpat
Somehow the condition got copied to the wrong line in #343 and nucked another field.
=> patterns: Fix incorrect condition in iso pattern

README.md, patterns/7z.hexpat, patterns/nro.hexpat, patterns/ogg.hexpat, patterns/ttf.hexpat, patterns/zip.hexpat
Here's a few more small changes after #321 :)
=> More misc cleanups

includes/hex/dec.pat
Fixes: https://github.com/WerWolv/Documentation/issues/30.
=> Update `hex::dec::zlib_decompress` description

README.md
Somehow missed that there is another column when adding the new line.
=> readme: fix table formatting

themes/Nocturne.json
minimal dark theme based on Dracula but more darker
=> Add Nocture theme

includes/std/ctype.pat, patterns/bencode.hexpat
This pull request contains several fixes for the existing Bencode pattern, and also a fix for the std::ctype pattern.
=> Fixes for bencode pattern

patterns/upk-ue3.hexpat
Just filling in the missing magic pattern
=> patterns/upk-ue3: Add magic pragma
