WerWolv/ImHex-Patterns

patterns/elf.hexpat

The e_ident field of ELF header isn't just the four first bytes that composes the magic number "0x7f ELF", it's actually an array with a size of EI_NIDENT (= 16) bytes (see "man elf").

Fixed ELF header pattern

---

README.md
patterns/wav.hexpat
patterns/zip.hexpat

Pattern for zip file parses End of Central Directory Header and Central Directory File Headers
Pattern for wav file parses RIFF header, WAVE header, and PCM header

Patterns for .zip files and .wav files

---

magic/portable_executable_magic
patterns/pe.hexpat

Some Windows users may have .exe MIME type which isn't application/x-dosexec.
This PR adds pragma for the two other main MIME types used by PE files.
(It was the reason for my ImHex installation to not show up the patterns popup when opening a Portable-Executable file.)

Fix : Added pragma for multiple PE MIME types.

---

README.md
patterns/elf.hexpat
patterns/pe.hexpat

ELF binaries sometimes are shared libraries rather executables. To address this issue, `application/x-sharedlib` pragma was added top of elf.hexpat file.
Also, README.md has been updated to follow current PR and previous PR, where I forgot to add Portable Executable into Magic files entries.

Handles application/x-sharedlib mime-type as ELF binary

---

patterns/pe.hexpat

Fixed a typo where it said numberOfRelactions to numberOfRelocations.

patterns: Fix typo in pe.hexpat

---

patterns/pe.hexpat

The current pattern file for the PE format doesn't have a lot of the format's quirks, so I decided to code them in after I noticed that it doesn't cover the structure known as Rich Header. (Forgive the garbage code for its ProductType enum, it was the only way I found to make the values appear.)
I changed the MIME type to x-msdownload so that it supports PE file extensions other than .exe.
Here are my sources for the improvements included here:
How the MZ header works and some of its variables' names: [How to determine the size of an PE executable file from headers and or footers](https://stackoverflow.com/questions/34684660/how-to-determine-the-size-of-an-pe-executable-file-from-headers-and-or-footers)
The function of some of the MZ header variables: [PE102 by …

Add enhancements for pe.hexpat

---

patterns/elf.hexpat

https://github.com/torvalds/linux/blob/master/include/uapi/linux/elf.h#L38-L41
I'm unsure if this file format allows for exclusion of the namespace so I included it just in case

patterns: Add GNU program types to ELF

---

README.md
patterns/id3.hexpat

I found the patterns for OGG and Vorbis useful when developing a custom metadata tag parser, but there was none for ID3, so I created one.
It's still missing support for extended header data, but I have no such files in my library.

Add pattern for ID3 tags

---

patterns/pe.hexpat

Hi! Bringing in a ton of additions, including:
- Code for the Resource/.rsrc section has all the values other than the header now;
- Statement `Product products[while($ != richHeaderEndPosition)];` in the code for the Rich Header was changed to use `<` instead;
- Debug and CRT sections were implemented;
- The code declaring sections was touched up;
- Code for the DOS stub is now more accurate;
And a few other things that were fixed, such as the Read-only data Section's code. I know that it doesn't work that way as do sections in general, but trying to implement that took too long. This is only for publishing the fixes that have been already made.

Making pe.hexpat even better

---

patterns/zip.hexpat

I did some minor cosmetic changes to zip.hexpat: cleanup whitespace, remove an unused struct, and shorten a giant field comment that was causing a tooltip wider than my screen.
I'm sending this PR to keep these minor changes separate from my actual additions later :)
By the way, I see most commit messages start with the directory/category name like "patterns:". I did the same for consistency, but if only touching one file, wouldn't it make more sense to put the format name there? Like "png: Add sRGB chunk support".

Minor cleanup to zip pattern

---

patterns/zip.hexpat

Previously, the zip pattern was searching for the end-of-central-directory header signature (50 4B 05 06) by searching the entire file for it. This is *very* slow for large files, and risks false positives since those bytes could randomly appear in compressed data. I had this happen on the first large (>2GB) zip file I tried.
I'm now checking for the EOCD signature at exactly 22 bytes from the end of the file (in the common case there is no zip comment), and if that fails I search for it in the last 64KB of the file (in case there *is* a comment at the end of the EOCD, which can't be larger than 64KB). This is much faster, and fixes loading my zip file where it was spuriously finding the signature in the wrong place.
This still has a low risk of false positives (what if the comment has …

zip: Change how the end of central directory record is found

---

patterns/pbzx.hexpat

This is used by Apple for Xcode .xip files (cpio in pbzx in xar), OTA updates of iOS, and other files.

Add pattern file for Apple PBZX compressed streams

---

includes/std/limits.pat

Added missing namespace to `std::limits::s*_max()`.

includes/std: Fix namespacing for std::limits::s*_max()

---

README.md
patterns/dmg.hexpat

This adds the struct/pattern for Apple Disk Images's trailer object (.dmg). This could be further extended by decoding the XML identified as `metadata_plist`, decoding the base64 payload within that and parsing those structs and the compressed objects they relate to if base64 & XML could be added to the[ ImHex decoding library](https://imhex.werwolv.net/docs/libraries/hex/hex_dec.html#decoding-library-1-24-0). 🤔
- Try to keep this file below ~ 1 MB

patterns/dmg: Added DMG pattern

---

patterns/qoi.hexpat

Just figured out the bit fields weren't read correctly.

fix qoi.hexpat: bitfields order

---

patterns/tar.hexpat

There are two common magic values for archives: the [GNU one](https://git.savannah.gnu.org/cgit/tar.git/tree/src/tar.h#n160) (8 bytes) and the [ustar one](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/pax.html#tag_20_92_13_06) (6 bytes).
This change has the pattern support both.

patterns/tar: support PAX archives

---

patterns/nbt.hexpat

The pattern code for the IntArray and LongArray tags were missing in the NBT.hexpad

Added missing int array and long array tag

---

includes/type/ip.pat

This fixes the IPv6 type by importing the string library for the format function, and forcing the words to have the network order.
Leading zeros have also been removed from the formatted string, because they are not necessary when displaying in short form.

Fix the IPv6 type

---

includes/type/leb128.pat

Add support for signed LEB128 type in the standard type library.
Also added documentation to the Pattern Language Docs: WerWolv/PatternLanguage#26

Add signed LEB128 type support

---

patterns/elf.hexpat

`SHT_SYMTAB` follows the same format as `SHT_DYNSYM`, please refer to page 1-12 of ELF file format spec: https://refspecs.linuxbase.org/elf/elf.pdf

ELF: treat SHT_SYMTAB as symbol tables

---

patterns/dex.hexpat

Added string representations for:
- string ids
- field ids
- method ids
- class ids
- proto ids
Example display:
I left the `class_data_item *class_data_off:u32;` line commented out because it increases parsing time so much. In my test dex sample 0.5 to 3.5 seconds

add more information to display for dex pattern

---

includes/std/core.pat
patterns/elf.hexpat

**DO NOT MERGE BEFORE THE CORRESPONDING PATTERN LANGUAGE PULL REQUEST**
https://github.com/WerWolv/PatternLanguage/pull/29
Since ELF file has ~30 sections and ~8 segments all with similar structures, it gets very ambiguous in Hex Editor view:
What section/segment do each of `p_data` and `data` belong to?
To figure it out the ImHex user ends up jumping back and forth between Hex Editor and Pattern Data views and clicking to expand each section/segment header as they are not highlighted when you highlight some byte in Hex Editor view.
We add a post processing step to set the display names for all data data arrays to the notations that mention both section index and name, index and type for segments. Unfortunately it has to be a post processing step as string table with all of the names is …

ELF: make hex view less ambiguous

---

includes/std/ptr.pat

An implementation of nullable pointers was discussed briefly on discord; WerWolv suggested the implementation in the example code here that's ostensibly generic over the pointer type/size, but the template system doesn't seem to like this special case where a type argument is used as a pointer type (the code below returns the error `Pointer size needs to be a built-in type`, with the error being directed at `T *data : Size;`):
```
struct NullablePtr<T, Size> {
Size pointerValue [[no_unique_address, hidden]];
if (pointerValue == 0x0) {
padding[sizeof(Size)];
} else {
T *data : Size;
}
};
```
So I specialized the structure to the common 2^n pointer types. I'll leave it up to WerWolv /  maintainers whether they want to use this specialized version, do something else, or just forego adding …

Add nullable pointers to std/ptr

---

includes/std/math.pat

Removed extraneous argument base to ln function and added the necessary definition in include file to access previously builtin function exp.

Recently added exp function needs to be added to math include

---

patterns/gif.hexpat

Hey :)
I was trying to fix a malformed GIF and found the pattern to be a little lacking so I improved it a bit.
This PR contains the following:
- Changed some structs names, and the way they are parsed to be consistent with the [89a specification.](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)
- Removed function implementations that were already in the standard library.
- Added a MAGIC assert and some warnings when unexpected patterns are found.
- Removed un-helpful `[[comment]]` and `[[hidden]]` tags.
- Cleaned the code from commented TODOs and commented out lines.

Improved GIF pattern

---

patterns/java_class.hexpat

Format bytecode instructions into a human-readable format.
But there are some problems:
1. code_length describes the byte length of the instructions, but the instruction is variable length, so the length of the instruction array will not match the `code_length`.
2. Lines 1036-1047 use `addressof(parent)`, and what is expected is the starting address of the `code` array in `attribute_code`, but it is actually 8 bytes less.
It works, but possible to optimize.

pattern/java_class: Format byte code instruction

---

patterns/dex.hexpat

Rather than a Fix, this is more additional support to see more inside the DEX file format.

Fix pattern to see data section of DEX files + Link_data

---

patterns/bmp.hexpat

- Add various version of the BitmapInfoHeader struct, and autodetect the correct one.
- Fix palette detection.
- Use BitmapInfoHeader::biSize to find the position of the palette / data.

patterns/bmp: various improvements

---

patterns/fdt.hexpat

In order to have a better time viewing FDTs in the visualizer scanner will now unflatten the FDT.
It could still be improved slightly by detecting whether they should be u64s.

Unflatten FDT

---

patterns/pe.hexpat

majorVersion/minorVersion fields in the DebugDirectory are incorrect, they are actually u16.

Fix DebugDirectory version field types

---

patterns/vhdx.hexpat

* Replaced `right_to_left` to `bitfield_order`
* Fixed type of `ParentLocatorEntry` (`char` -> `char16`)
* Fixed item address of `MetadataTableEntry`
* Improved `RegionTableEntry`

patterns/vhdx: Various improvements

---

patterns/bson.hexpat

BSON files can contain consecutive documents glued one after another. An example of these is MongoDB FTDC metrics export.
[`bsondump`](https://github.com/mongodb/mongo-tools/blob/master/bsondump/bsondump.go) can unpack this type of BSON documents.

BSON support for multiple documents per file

---

README.md
patterns/nes.hexpat

Hello, I'm here with a pattern file for the .nes file format. This is the one initially conceived as the iNES format by Marat Fayzullin for files with NES game roms.
Credits go to 100th_Coin for telling me about where the entry point is located and Gilde for transcribing a kanji that described the complementaryChecksum variable.

Add .nes pattern file

---

patterns/id3.hexpat

- macOS Ventura 13.2
- ImHex Hex Editor v1.30.1
The console showed the error message `No variable named 'n' found.` when I opened an MP3 file with ID3 v2.4.0 tag and imported the ID3 pattern.
After tweaking the pattern, I found two ways to resolve the error:
- Remove the `ref` keyword from the argument `n` for the function `ssi_value`
- Use `size` as the variable name inside the function `ssi_value` (I changed the argument name to `size` too but it can be any name or even left empty)
I don't know which way is preferable. Maybe the problem is in the core library so the pattern file should not be changed at all. I have little knowledge about the behavior so I just opened the PR to see if it solves anything. Thanks for the good work and I enjoy the editor very much!

patterns/id3: Fix the error `No variable named 'n' found.`

---

patterns/zip.hexpat

Introduce parsing of local file headers.
Introduce compression method header support.
Make minor adjustments: remove black colors and mark magic IDs.

patterns/zip: add parsing local file header with minor adjustment

---

patterns/flac.hexpat

- Adds `METADATA_BLOCK_SEEKTABLE` to `METADATA_BLOCK`
Without `METADATA_BLOCK_SEEKTABLE` in this, the pattern errors

patterns/flac: Fix SEEKTABLE metadata block

---

patterns/ip.hexpat

The orginal code was considering the IP header and TCP header has fixed lenght of 40 bytes. Actually it should be calculated by related header fileds in order to support any valid TCP packets.

fix payload size when ip header or tcp header has options in ip.hexpat

---

patterns/intel_hex.hexpat
patterns/uf2.hexpat

Some description pragmas still had a markdown link syntax

patterns: fix description pragmas

---

patterns/jpeg.hexpat

patterns/jpeg: small improvements

---

patterns/mp4.hexpat

handler_type is actually a 4 character string, so it better be represented as a char[4] (instead of u32)
example values are "soun" and "vide", here is a list of possible values
https://cconcolato.github.io/mp4ra/handler.html
Screenshot of handler_type="soun" (when changed to char[4])

MP4: make handler_type into a char[4], which reflects how it is used

---

patterns/mp4.hexpat

Previously the mp4 pattern could only see the existence of STBL boxes, with this PR it can also see child boxes inside
It also adds  support for the SampleDescriptionBox(STSD), which contain information about which codec is used. "mp4a" and "avc1" in this examples below
[mp4a](https://en.wikipedia.org/?title=Mp4a&redirect=no):
[avc1](https://en.wikipedia.org/wiki/Advanced_Video_Coding):

MP4: Add childbox support for STBL boxes

---

includes/std/string.pat

The previous fixes for this function didn't consider the case when the resulting string has a contribution from the original string that occurs after all the substitutions have been made and that is longer than the replacement string. This PR resolves that issue and also addresses the case where one or more of the inputs is empty. Please see discussion on [ImHex issue #1408](https://github.com/WerWolv/ImHex/issues/1408) for details.

fix:  [ImHex Bug] std::string::replace("aa", "aa", "") returns "a" #1408

---

patterns/mp4.hexpat

Support for avc1(h264) and mp4a(aac) codecs
Can extract things like width and height of the video, and sample_rate of the audio
Example of Avc1 info (width and height)
Example of mp4a (sample_rate)
Also the (sample)TimeToSample "stts"box is implemented

MP4: Support mp4a and avc1 codec boxes

---

patterns/mp4.hexpat

Add support for some of the most common child boxes of STBL(Sample Table Box)
The child boxes implemented are the most common ones that are included in the output of video-files produced by for example FFmpeg. 
For reference information of the childboxes, see the [ISO-base media file format](https://b.goeswhere.com/ISO_IEC_14496-12_2015.pdf) on which MP4 is defined.
For overview see page 16 (page number in the bottom of the page, not PDF-page number)
CTTS, CompositionOffsetBox, is on page 37
STSS, SyncSampleBox is on page 40
STSC, SampleToChunkBox is on page 48
STCO, ChunkOffsetBox, is on page 49

MP4: Add STBL-box children

---

patterns/pe.hexpat

on arch linux, libmagick detects pe files mime as "application/vnd.microsoft.portable-executable"

add pe mime for arch linux

---

patterns/bgcode.hexpat

Support for binary G-code files, used by 3d printers

patterns: Add .bgcode file

---

README.md
patterns/refs.hexpat

+ Added refs.hexpat in `patterns/refs.hexpat` in 5h4rrK branch
+ Updated README.md 
+  Sample ReFS file System file : `https://github.com/teambi0s/bi0sCTF/tree/main/2024/Forensics/ReAL-File-System/handout`
+ References
-  **ARIN** : `https://github.com/horensic/ARIN`
- **ReFS Reverse Engineering** : `https://www.sciencedirect.com/science/article/pii/S1742287619301252`
+ Image

Added Pattern File For Parsing ReFS filesystem Header, SuperBlock and CheckPoint

---

includes/std/core.pat
includes/std/math.pat
includes/std/mem.pat
includes/std/random.pat
includes/std/time.pat

In early 2023, `builtin::std::core::get_attribute_value(pattern, attribute)` was changed to `builtin::std::core::get_attribute_argument(pattern, attribute, index)`, and a third parameter was added to that function.
"*includes/std/core.pat*" was never updated for either of those things, causing compile errors when using `std::core::get_attribute_value` in a pattern.
This pull request updates that file to add `std::core::get_attribute_argument(pattern, attribute, [index])` (with `index` defaulting to 0), and makes `std::core::get_attribute_value` show you an error telling you to use `std::core::get_attribute_argument` instead. (I would've made `std::core::get_attribute_value` use an index of 0, but given that it's been broken for over a year, I don't think that a lot of current patterns use …

Replace get_attribute_value with get_attribute_argument

---

patterns/refs.hexpat

+ Added Filesystem Checking before parsing it.
+ Added Comments in VBR, META_HEADERS, Superblock & Checkpoint
+ Changed `REFS_HEADER` to `VOLUME_BOOT_RECORD`
+ Fixed Typo

Added filesystem Checking, comments, Renamed REFS_HEADER, and Fixed typo.

---

patterns/refs.hexpat

+ Added Structure for MinStoreB+ Node `(MSB+)`. Parses MSB+ nodes for `ContainerTable`, `ContainerTableDup` and `SmallAllocatorTable`.
+ Parses all `SuperBlocks`. 
+ Added missing `GlobalRootName`.
+ Added few missing structures in VBR, SuperBlock & CheckPoint.

Added Structure for MinStoreB+ node, missing GlobalRootNode Names & parses all Superblocks

---

patterns/7z.hexpat

without this imhex don't detect .7z files (archlinux flatpak)

Add 7z MIME

---

patterns/wintec_tes.hexpat

With this pull request, I'm adding support for a very simple (if somewhat obscure) file format for a specific GPS Tracker from the early 2000s. The device itself is no longer being sold.
The pattern itself makes use of a lot of the functionality on top of this simple file format. Maybe it is useful as an example for other pattern files. Specifically, it adds colors, comments and formatters for most fields.
Also referencing discussion #234

Adding the hexpat for Wintec TES files

---

includes/hex/core.pat

This function is implemented [here](https://github.com/WerWolv/ImHex/blob/master/plugins/builtin/source/content/pl_builtin_functions.cpp#L32-L45), yet is never directly exposed using the hex/core.pat pattern file.

Add add_virtual_file to hex/core.pat

---

includes/std/file.pat

The std::file::flush function called the builtin remove function instead of the builtin flush function, meaning that any call to flush would actually delete the file

Correctly call builtin flush

---

patterns/mp4.hexpat

According to ISO/IEC 14496-12, the width and height fields should be fixed point 16.16.
* Use FixedPoint32 instead of u32 for width and height
* Add formatting for displaying fixed point 16.16 and 8.8 numbers

mp4: Use FixedPoint32 instead of u32 for width and height

---

patterns/pe.hexpat

This code works and can be used with binaries using PE (exe files) and a delayed dll loader section called .didata:

patterns/pe added .didata section support

---

includes/std/sys.pat
includes/type/path.pat

1. Escape backslash in DOSPath docs. Thanks to @vlenhart for noticing the error here: https://github.com/WerWolv/Documentation/pull/9
2. Spelling correction for std\sys.pat. Thanks to @bluestonethe2nd for submitting a PR here: https://github.com/WerWolv/Documentation/pull/14

Add some fixes from the WerWolv/Documentation repo

---

README.md

Forgot to double check the README links in the last PR, should be fixed now. Thanks @mandar1jn for letting me know.

readme: fix hinf_tag and hinf_module links

---

includes/std/core.pat
includes/std/mem.pat
includes/std/string.pat
includes/std/sys.pat
includes/type/byte.pat
includes/type/path.pat

I saw this issue: https://github.com/WerWolv/ImHex/issues/1139. I ran through the standard library patterns and fixed all the spelling errors I caught with the VSCode's Code Spell Checker plugin.

Fix some spelling errors

---

patterns/fbx.hexpat

I split the fix and some improvements into two separate commits. Both should be functionally the same and I would have expected both to be fully working but the first commit does not work and the second one does. I'm not sure why my weird workaround actually works but it should be in a useful state now.

patterns: FBX - fixed the fbx hexpat

---

patterns/fbx.hexpat

The switching between A and B type NodeRecords turned out to be unnecessary.

patterns: FBX - simplified the fbx hexpat

---

includes/std/core.pat

Probably a copy-paste issue - std::core::set_pattern_comment has a parameter `comment`, but was using (and the comment was documenting) `name`

Update core.pat - fix set_pattern_comment

---

patterns/msgpack.hexpat

* 16-bit and 32-bit extension lengths were not marked big-endian.
* Negative fixint values were being mangled.

Fix msgpack bugs

---

patterns/coff.hexpat

this now behaves like the pe pattern
see specification: https://learn.microsoft.com/en-us/windows/win32/debug/pe-format#section-flags

fix off by one error in coff pattern

---

patterns/pe.hexpat

while the previous way seemed to work it should be more robust to use the ptrRawData to place the start of sections

use appropriate pointer for first section placement

---

README.md
patterns/loc.hexpat

Used for storing language strings, I have no example file as of yet as I haven't made a writer for it.

Minecraft LCE LOC file

---

patterns/zip.hexpat

Add "GeneralPurposeBitFlags" bitfield definition to the ZIP pattern. The names are based on the official ZIP format specification, although I chose to name the fields closer to their purpose rather than their official name. This is intended to make reading the pattern and its output easier. Example: official name "Language encoding flag (EFS)" my name "filenameAndCommentAreUtf8" because this immediately explains what it does.
I chose not to implement the specifics of the "compressionOptions" as their meanings are specific to the compression method used, and it would make the pattern much more complicated for (in my opinion) little gain.
I also chose to unify the names of the general purpose bit filed in the LocalFileHeader and the CentralDirectoryFileHeader. Previously, they had different …

Add parsing of general purpose bit flag in ZIP pattern

---

patterns/pe.hexpat

Export table might not exist in pe exe. if  ordinalTableRVA is zero. pattern will failed to parse

Fix pe not working when ordinalTableRVA is zero

---

README.md
patterns/gb.hexpat
patterns/gba.hexpat

Hello, this PR adds:
- Game Boy Advance (GBA) hexpat.
No test files could be included due to copyright.

Patterns/GBA Header

---

patterns/bzip3.hexpat

Hi there.
Noticed a small thing, since I started fuzz testing bzip3 this morning.
Turns out I was branching on the wrong field; made an accidental error, because testing tiny files (< 64 bit) is rare.
Oopsie. In any case; this trivial fix should do it.

Fixed: Incorrect field on branch in bzip3

---

includes/type/leb128.pat

1. 0x80 0x40 is -8192 (-0x2000) in signed leb128, but the pattern language thinks it is 8192
2. 0xFF 0x3F is 8191 (0x1fff) in signed leb128, but the pattern language thinks it is -8193
The detection of the sign bit was wrong.

Fix parsing of signed leb128

---

patterns/iso.hexpat

Primarily it parses all volume descriptors and not just the first one. To do that it always allocates enough padding to reach a length of 2 KiB.
I also tried adding support for the supplementary volume descriptors assuming that it is using Joliet. I'm not sure if that second part fits the code quality of this repository and I can separate it into another pull request if requested: It might contain other encodings depending in the contents of the escape sequences.

Add some improvements to the ISO pattern matching

---

patterns/protobuf.hexpat

In issue #346  it is noted that the format functions return the same value repeatedly and erroneously. This is due to the use  of global variables which result on only their last value being used in format functions due to their delayed evaluation. Fixed by using local variables instead. Also remove tabs from the file and an unused tags variable.

fix: fixes issue #346

---

README.md
patterns/rpm.hexpat

First attempt at implementing RPM package file format in pattern language. Would like your review and critique.
File spec: http://ftp.rpm.org/max-rpm/s1-rpm-file-format-rpm-file-format.html
Would also note that I decided not to patternize LZMA archive which is in this file too. Firstly it is an RPM and it already has a lot of patterns. Secondly LZMA should be separate pattern

patterns: Add RPM pattern

---

README.md
patterns/upk-ue3.hexpat

Unfortunately, no test data added.
The UPKs I have on hand are from game files, and their filesizes are pretty large anyway.
Should otherwise be fine though.

patterns: Add Unreal Engine 3 UPK pattern

---

patterns/elf.hexpat

use e_shstrndx to get section names instead of guessing

---

patterns/elf.hexpat

for some reason the `set_endian` in the elf struct does not take effect. big endian elf files are not parsed correctly. setting the endianness globally fixes the issue.

fix: Set elf endianness globally

---

patterns/zip.hexpat

Some zip files have their extra fields padded at the end  (such as apks processed by [zipalign](https://cs.android.com/android/platform/superproject/main/+/main:build/make/tools/zipalign/ZipEntry.cpp;l=210;drc=9c843a66d11d85e1f69e944f1b37314d3e47aab1))

patterns/zip: Handling padded extra fields

---

README.md
patterns/stdfv4.hexpat

The [Standard test data format](https://en.wikipedia.org/wiki/Standard_Test_Data_Format) is defined to keep track of testing data during chip manufacturing and used by almost all tester manufacturers. The official documentation can be found at http://www.kanwoda.com/wp-content/uploads/2015/05/std-spec.pdf.
I tested it with an example published by Roos (https://roos.com/docs/RBEH-AH4R8T?Open) but did not include that in the PR as they list it as "confidential and proprietary" (though I find "confidential" an interesting statement for smthg hosted publicly...).
I also tested it multiple internal files from other vendors, which I can't share. I'm checking with a colleague whether they can provide some small file that doesn't include any proprietary information but my hopes are not too high - …

patterns: Add STDFv4 pattern

---

patterns/pe.hexpat

Check for `imageNameRVA` in `pe.hexpat` before reading `imageName`

---

patterns/uf2.hexpat

Adds a `#pragma magic` from the [spec](https://github.com/microsoft/uf2#file-format) so UF2 files can be auto-detected.

Add magic number for UF2 pattern

---

README.md
patterns/rcf_v1_2.hexpat

Tested games:
- Hulk (PS2)
- Tetris Worlds (Gamecube)
- The Simpsons Hit and Run (PC)

Add Radcore Cement v1.2 file pattern

---

patterns/wintec_tes.hexpat

When viewing a wintec file, it typically consists of hundreds of entries line by line. I found out that any entry can be formatted, so the lines themselves now also get a readable string. This now looks like this:
(it used to display just `{ ... }` in the Value-column)

pattern wintec_tes: slightly nicer formatting in a list of entries

---

README.md
patterns/exfat.hexpat

Requested by #108 
This PR add support for the exFAT filesystem
While I have encountered many crashes using this software, thanks to your software, I was able to recover images from a corrupted exFAT filesystem in a SD card
After few attempts of refactoring the code, I would like to contribute back to the community with the pattern I have written

patterns: Add support for exFAT

---

patterns/mp4.hexpat

The current implementation of mp4-pattern is very slow to deal with any larger mp4 files. Even loading a 50 megabyte mp4 video file is very slow and takes many minutes on a modern computer
The problem is the "mdat"  or MediaData box which is the biggest box contaning the raw media data have a very to slow implementation in the mp4-pattern language file.
This PR replaces the "mdat" box implementation with a much faster one, that so that we can work with files gigabytes in size instead of just 50 megabytes before everything gets way to slow
Here is an example mp4 file of 270 megbyte
https://www.peach.themazzone.com/durian/movies/sintel-2048-surround.mp4
(found [here](https://durian.blender.org/download/))
Open it with the existing mp4-pattern. It take many minutes to open, if it manages to …

Add support for medium and large mp4 files

---

themes/Nocturne.json
themes/one_dark.json

Both one-dark and nocturne used global-doc-comment instead of the correctly named doc-global-comment. Typos in Nocturned didn't prevent the theme from loading, but left annoying messages in the log. As explained by the author, the base colormap must be one of the three that imhex loads by default, dark,light and/or classic.

fix: issues with two remaining themes.

---

patterns/q3demo.hexpat

If the game crashes while writing a demo, it can end up cut off at the end. Added a small safeguard against it so that that final corrupted message will simply be ignored.

Quake 3 demos: Handle corrupted files more gracefully

---

patterns/fs/ext4.hexpat

When `s_first_data_block` is 1, the table is located at block 2 (how it was hard-coded before), but when `s_first_data_block` is 0, the table is at block 1.
This caused the the pattern parsing to fail on file systems with non-1024 sized blocks.

Fix ext4 pattern group descriptor table location for non-1024 block sizes
